### PR TITLE
Update PlaceholderDataSourceDelegate.swift

### PR DESCRIPTION
**Pull request by m7md3elwan**
Hello 

I'am proposing to subtract tableHeaderView height out of the height of calculated frame height

screen shot 2017-08-04 at 3 40 40 am

### CODE REVIEW

**Comment by HamzaGhazouani** [comment]
Hi @m7md3elwan, thank you for your contribution.
Good point, but we should not change the placeholder size but hide the tableViewHeader and tableViewFooter.

**Comment by HamzaGhazouani** [comment]
@m7md3elwan I pushed a new version supporting header and footer, tell me if it's what you look for. Thanks

**Comment by m7md3elwan** [comment]
I think it will be great to have both options because i may have a case where i want user to know what i'am fetching

**Comment by HamzaGhazouani** [comment]
Hi @m7md3elwan, yes I think it could be a good feature to have an option to keep the header when the placeholder is shown, could you please update your PR with the latest code? thanks

**Pull request closed without merging**
